### APIs

In [6]:
!pip install pycoingecko
from pycoingecko import CoinGeckoAPI

Requirement already satisfied: pycoingecko in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (3.2.0)
Requirement already satisfied: requests in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from pycoingecko) (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests->pycoingecko) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests->pycoingecko) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests->pycoingecko) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests->pycoingecko) (2026.2.25)

In [9]:
cg=CoinGeckoAPI()
bitcoin_data=cg.get_coin_market_chart_by_id(id="bitcoin",vs_currency="usd",days=30)
print(bitcoin_data)

{'prices': [[1776348031437, 73705.01360985098], [1776351628941, 73938.04397589041], [1776355218900, 74740.25080601992], [1776358848233, 74214.42990809566], [1776362426081, 74273.00358424732], [1776366040853, 75017.42674367223], [1776369623094, 75389.68135904678], [1776373242253, 75240.31590673576], [1776376827315, 74944.91566812144], [1776380458176, 74883.21300083205], [1776384030955, 75149.1930221427], [1776387653697, 74977.75409490333], [1776391222764, 74787.851905865], [1776394807573, 74695.48255658832], [1776398432051, 74649.52985426539], [1776402060216, 74792.21540789708], [1776405653685, 74666.08972542649], [1776409248343, 74913.00922361523], [1776412817378, 75044.90134871528], [1776416471858, 75739.35058143485], [1776420035344, 75797.67899200699], [1776423613677, 75297.00919396247], [1776427227085, 75589.10032806055], [1776430804590, 76213.45555656118], [1776434480758, 77361.36237765808], [1776438058285, 77956.91427499668], [1776441669527, 77828.185699857], [1776445275036, 77862.89905005145], [1776448831603, 77498.81630549654], [1776452452485, 77164.03670386429], [1776456054342, 77436.59527540709], [1776459640617, 77362.87288021417], [1776463262842, 77496.71066229149], [1776466869578, 77308.43885337995], [1776470415387, 77128.44334858148], [1776474028704, 77169.64712633878], [1776477612377, 77201.78314338902], [1776481253738, 77315.4096324451], [1776484838295, 77013.53238285403], [1776488451751, 77158.48113774008], [1776492024127, 77152.68049883858], [1776495636584, 77131.3006381946], [1776499225517, 76998.06796704927], [1776502839772, 76755.0998125113], [1776506408049, 76617.80623429554], [1776510045450, 76188.45755869409], [1776513657316, 76072.68979550186], [1776517263736, 76224.9598173141], [1776520825301, 76137.19860160364], [1776524426751, 76251.58670751007], [1776528012360, 76181.98651177097], [1776531647226, 75927.57132288165], [1776535253230, 75864.95221180288], [1776538809275, 75653.54136303878], [1776542456722, 75670.66377392902], [1776546030982, 75757.95160113281], [1776549620269, 75828.32687513834], [1776553247003, 75830.19171188552], [1776556819243, 75728.45681761758], [1776560455762, 75652.21984514158], [1776564038652, 75642.12663561944], [1776567677341, 75558.77945979389], [1776571274063, 75540.50887836353], [1776574835911, 75681.49533537882], [1776578435261, 75569.83917977821], [1776582067182, 75407.80704076507], [1776585633524, 75295.98459973742], [1776589204218, 75244.24719211207], [1776592859248, 75020.97270538584], [1776596455940, 75236.36654292562], [1776600037294, 75599.26577131222], [1776603641851, 75624.6529610848], [1776607228888, 75920.89178630568], [1776610803231, 76024.76202757412], [1776614420279, 75840.65451654213], [1776618018075, 75495.36817299578], [1776621636729, 74800.94102146984], [1776625255283, 74795.1465182244], [1776628843659, 74974.34476516958], [1776632446413, 74689.24400809643], [1776636018388, 74460.14184607656], [1776639679302, 74137.21873636951], [1776643248126, 73856.05501487634], [1776646850777, 74346.05375810764], [1776650444180, 74623.05265769569], [1776654004643, 74458.21813860718], [1776657622245, 74653.54610763465], [1776661238550, 74581.28237935815], [1776664852141, 74277.51462154883], [1776668432318, 74789.56984853405], [1776672052000, 74795.97600729625], [1776675613386, 74741.97729093608], [1776679246167, 75062.12403807922], [1776682847491, 75045.02524645194], [1776686430682, 75179.56431310959], [1776690046403, 75285.69738107114], [1776693621627, 75290.96918392694], [1776697264999, 75004.42275652137], [1776700811000, 75687.721421251], [1776704431977, 75340.28666497084], [1776708026267, 75921.15197965335], [1776711659005, 76437.62877231697], [1776715240654, 76314.88533036472], [1776718882441, 76302.84677235561], [1776722442504, 75970.00268011336], [1776726009650, 75992.70086029985], [1776729634491, 75874.54629352967], [1776733242456, 76085.88237404238], [1776736856297, 75921.29817954023], [1776740455464, 75628.03723799669], [1776744058013, 75728.13586903199], [1776747632588, 75814.67217221636], [1776751272730, 75832.33172653822], [1776754841651, 76008.88286643253], [1776758435784, 76125.0717533993], [1776762008063, 76542.40965523037], [1776765649642, 76367.38771266557], [1776769225300, 76784.39417696862], [1776772813537, 76479.91862901945], [1776776460137, 75992.30702339568], [1776780036415, 75911.10361927166], [1776783616380, 75762.711638902], [1776787226659, 75803.94428247478], [1776790847102, 75861.34549918868], [1776794477084, 75556.47668629252], [1776798040192, 75598.61267682334], [1776801652473, 74995.37782854948], [1776805241688, 75763.05667180788], [1776808832686, 75574.10377442642], [1776812427372, 75629.08968346077], [1776816037205, 76350.25202878818], [1776819623839, 76308.7293299303], [1776823255707, 76322.61641898053], [1776826854527, 77536.75470746626], [1776830440948, 77587.83202645402], [1776834047209, 77478.20552898936], [1776837657207, 78016.40224612548], [1776841210741, 77988.76554637455], [1776844851547, 78067.63707556471], [1776848457778, 78058.08975780573], [1776852056646, 78024.52473191661], [1776855646807, 78144.37988534916], [1776859256988, 78287.86829838748], [1776862800597, 78273.8966848666], [1776866403201, 78815.99780735128], [1776870016489, 79080.63292286295], [1776873664024, 79321.15968354288], [1776877225757, 78751.70323522005], [1776880850652, 78923.92967916405], [1776884435409, 79026.34137679906], [1776888052843, 78946.3912548935], [1776891652677, 78453.79426420951], [1776895205923, 78791.52632630398], [1776898843763, 78602.89731358779], [1776902440823, 78194.78334884858], [1776906048116, 78406.2930435807], [1776909618441, 78357.18396749758], [1776913247770, 77985.92377137982], [1776916847486, 77745.85432228484], [1776920422561, 77935.74125864716], [1776924037500, 78027.34427996507], [1776927617638, 78224.5180282668], [1776931239673, 78031.99538001728], [1776934824199, 77897.87177343022], [1776938453511, 77638.50183036197], [1776942013367, 77421.70696946804], [1776945660400, 77720.82903527566], [1776949200958, 77689.20240973093], [1776952803966, 77534.60343866517], [1776956461571, 78194.45325685579], [1776960035533, 78400.43360010415], [1776963672798, 78107.69300312691], [1776967235961, 77774.75239415659], [1776970841386, 77788.60996280434], [1776974471601, 77758.18784079723], [1776978071533, 77892.40295122238], [1776981652886, 77960.96780301731], [1776985243134, 78241.97434139495], [1776988855292, 78260.61998045091], [1776992429654, 78385.9994566751], [1776996008427, 78450.36540019314], [1776999647663, 78147.75938482724], [1777003251454, 77747.45626454431], [1777006841879, 77705.47025945061], [1777010430510, 77986.53527373911], [1777014051674, 77820.67157019368], [1777017652384, 77631.4765633673], [1777021250209, 77849.7374088029], [1777024808376, 77541.44001609184], [1777028457707, 77769.18978227278], [1777032048030, 78246.79964995776], [1777035660411, 78191.33520155153], [1777039244185, 78079.14695903476], [1777042836375, 78040.02364193133], [1777046444329, 78047.3380693329], [1777050031162, 77754.58226000571], [1777053646647, 77684.72881988292], [1777057205954, 77597.78722462713], [1777060822681, 77640.62590796669], [1777064428860, 77743.96821879945], [1777068076897, 77598.4707273492], [1777071651647, 77360.7247577714], [1777075232951, 77444.79563692068], [1777078840202, 77462.08912922682], [1777082455350, 77566.91332664572], [1777086070721, 77632.1049866153], [1777089671228, 77659.99727324375], [1777093226002, 77641.01117283583], [1777096804040, 77526.33855221451], [1777100461155, 77546.29139125944], [1777104027315, 77552.43014091096], [1777107657268, 77633.44423479457], [1777111256854, 77756.29359070981], [1777114849067, 77798.77053029239], [1777118449060, 77681.05139222337], [1777122035344, 77572.56576897178], [1777125659933, 77704.47912526024], [1777129265720, 77666.8630936243], [1777132836546, 77369.37427037527], [1777136412416, 77411.63283414992], [1777140028307, 77268.59468461889], [1777143647539, 77327.62457986774], [1777147231506, 77334.26544839946], [1777150812443, 77485.94368156035], [1777154433526, 77517.55017621993], [1777158026584, 77571.92469081761], [1777161643793, 77619.14219872655], [1777165225674, 77504.17855812809], [1777168803806, 77474.23663746598], [1777172445470, 77508.39871110146], [1777176012276, 77421.9680597692], [1777179641556, 77780.732585964], [1777183239567, 78011.43215971511], [1777186801656, 77968.04637604058], [1777190448885, 78104.00311325732], [1777194025361, 78046.40161728268], [1777197648136, 78007.27442207371], [1777201242207, 78005.02861473465], [1777204814977, 78110.88161863454], [1777208439504, 77838.15248676843], [1777212052097, 77940.84317164119], [1777215657502, 78104.22069639667], [1777219243334, 78050.75607592058], [1777222856563, 77985.65557780031], [1777226428642, 78034.51980737594], [1777230043789, 78274.34065021528], [1777233625299, 78240.93686631313], [1777237256720, 78229.8417681944], [1777240803843, 78407.16125498862], [1777244420641, 78378.05061328351], [1777248027238, 78645.12560170851], [1777251649775, 79260.26248669959], [1777255224503, 79217.03669448356], [1777258812333, 79161.16903469128], [1777262460515, 79096.32338375495], [1777266008318, 78918.2674998158], [1777269633628, 77819.8190965596], [1777273211988, 77728.11296302704], [1777276835326, 77653.42820403715], [1777280423824, 77801.48133620767], [1777284009832, 77918.22130374532], [1777287648733, 77858.06178429707], [1777291258779, 77839.13057125034], [1777294832811, 77636.7357570139], [1777298420954, 77767.52764704514], [1777302065894, 77816.0572264602], [1777305613302, 76772.56122738226], [1777309212461, 76597.37629170864], [1777312851604, 76701.61237959677], [1777316456805, 76840.12034837836], [1777320031438, 76829.48158520267], [1777323648838, 76986.58306724002], [1777327246196, 76798.22801186582], [1777330843889, 77068.29246494433], [1777334441441, 77361.29911038803], [1777338046510, 77383.54057877463], [1777341604023, 77090.31107128707], [1777345256701, 76833.05668971647], [1777348824854, 76804.77382356762], [1777352448493, 76884.15413049556], [1777356041954, 76948.09017415001], [1777359628376, 76711.2208351938], [1777363239870, 76871.94798938799], [1777366857917, 76823.96703050246], [1777370432750, 76582.2382436488], [1777374077572, 76587.46607990249], [1777377641615, 76182.61040738711], [1777381251576, 76342.5588428331], [1777384839320, 76180.39793452619], [1777388463316, 75849.31178726906], [1777392056195, 76040.86480284185], [1777395634217, 76108.79943793108], [1777399253791, 76174.499991253], [1777402876832, 76223.05617004436], [1777406476570, 76340.1341246333], [1777410076527, 76445.86122627115], [1777413677983, 76353.70892706158], [1777417275820, 76229.4038502392], [1777420879320, 76345.22521002527], [1777424477903, 76505.05470800745], [1777428056205, 76537.83594119303], [1777431667974, 76478.80195313173], [1777435222141, 76961.46963288501], [1777438802625, 77289.79308700348], [1777442438633, 77258.63042398472], [1777446031012, 76964.99741594712], [1777449611567, 77023.71023600476], [1777453259060, 77028.46347185198], [1777456873258, 77629.86690905425], [1777460469390, 77596.56363815261], [1777464054224, 77579.59487006326], [1777467638082, 77127.99638212805], [1777471262001, 76776.12526378022], [1777474843812, 76558.49021649477], [1777478461713, 75858.12862387307], [1777482054287, 75763.67004036404], [1777485628569, 75996.93512732009], [1777489255543, 75436.56581067356], [1777492847135, 75468.90041834336], [1777496409185, 75701.80458172278], [1777500034074, 75924.91798195371], [1777503640535, 75907.29950981027], [1777507246340, 75774.8855230121], [1777510821235, 76255.01364165342], [1777514424298, 76220.83380666314], [1777518017943, 75691.65564515392], [1777521641929, 75909.7088552133], [1777525238275, 75459.6526551717], [1777528838043, 75580.06196734082], [1777532451783, 75713.26283708648], [1777536059565, 76085.14106760567], [1777539634276, 76026.7764354485], [1777543243024, 76090.4726987875], [1777546848342, 75986.04492329038], [1777550421241, 76005.83880555014], [1777554064561, 76280.05036510443], [1777557650826, 76410.61364346408], [1777561229633, 76270.43468783535], [1777564859951, 76455.76704590907], [1777568448747, 76216.33823270486], [1777572024638, 76235.32221878375], [1777575642712, 76343.14131925348], [1777579239482, 76391.95833110265], [1777582850514, 76465.47268894286], [1777586444363, 76231.26886058506], [1777590011796, 76189.37205616337], [1777593600693, 76286.57710950871], [1777597253489, 76379.67128631244], [1777600847284, 76656.57064385938], [1777604401370, 76517.3133818177], [1777608010968, 77085.22718465359], [1777611622505, 77009.0736401404], [1777615238361, 77118.9788591889], [1777618840828, 77034.26419331781], [1777622426705, 77096.21079038092], [1777626021323, 77340.98047049128], [1777629616743, 77231.30471966216], [1777633254545, 77240.15798301293], [1777636845526, 77433.64205650402], [1777640442692, 77969.27491618901], [1777644070071, 78695.21355815475], [1777647613191, 78320.42975742156], [1777651249972, 78434.82448589527], [1777654803247, 78252.9324694872], [1777658452001, 78548.40091164663], [1777662031370, 78382.96178450093], [1777665628062, 78423.58948035864], [1777669239242, 77859.3116606549], [1777672849543, 78174.02675323762], [1777676456057, 78138.26976073837], [1777680033537, 78172.07422147921], [1777683636113, 78308.37520882013], [1777687244908, 78286.27861903312], [1777690811975, 78362.29923426916], [1777694439668, 78437.93476926665], [1777698006749, 78150.11936951149], [1777701628993, 78195.68680702572], [1777705245701, 78306.93283732959], [1777708848392, 78194.06055081423], [1777712440845, 78285.70832684374], [1777716047319, 78281.28398457692], [1777719647841, 78240.11769161666], [1777723241480, 78128.46024348195], [1777726852674, 78193.2744831238], [1777730423002, 78360.21898348848], [1777734057596, 78411.38510755789], [1777737633180, 78461.63721855872], [1777741211069, 78435.08617699439], [1777744804005, 78382.70991118148], [1777748446535, 78457.5389191646], [1777752015067, 78447.53632340279], [1777755647472, 78439.4139272263], [1777759224789, 78732.6338722369], [1777762835245, 78804.99536374844], [1777766459728, 78666.02056290468], [1777770056603, 78525.2146039029], [1777773628483, 78247.12211102132], [1777777266475, 78157.88034742486], [1777780854226, 78188.40860775959], [1777784457318, 78146.92223825728], [1777788049289, 78229.08291869442], [1777791668417, 78271.08132011641], [1777795238248, 78350.69027764065], [1777798857190, 78386.58845756314], [1777802456075, 78514.79652456472], [1777806033462, 78393.61348590766], [1777809611955, 78651.90783179233], [1777813228703, 78723.62272234702], [1777816856232, 78671.01722577176], [1777820425426, 78735.77368245517], [1777824001209, 78648.51670661499], [1777827643040, 78671.22481306917], [1777831264652, 78714.14816000318], [1777834829236, 78723.71597574794], [1777838406341, 78772.93638758908], [1777842024969, 78882.41352644576], [1777845602579, 78784.56538231378], [1777849218129, 79164.91262664807], [1777852824199, 78542.80803714818], [1777856421733, 78523.09209511426], [1777860011798, 79525.0486011737], [1777863647107, 80247.57433910447], [1777867219152, 80254.0760312916], [1777870804028, 80296.72362760552], [1777874449287, 80010.78689175253], [1777878026455, 79920.44749612657], [1777881653151, 79689.3122143952], [1777885252207, 79714.0128258611], [1777888851475, 79832.33782372707], [1777892430233, 78911.17072497762], [1777896029630, 78794.5386775698], [1777899646426, 78946.74382793218], [1777903219620, 78795.3827203887], [1777906826294, 80262.81441266934], [1777910459053, 79961.47965724225], [1777914029774, 79997.7587206583], [1777917624474, 80468.0775179202], [1777921225417, 80114.39169381397], [1777924836109, 80052.0708073038], [1777928449527, 79929.45608891523], [1777932046495, 80248.55770465586], [1777935654225, 80060.10705547684], [1777939220337, 79824.40331204748], [1777942842625, 80138.68119208484], [1777946436397, 80325.98978821686], [1777950042948, 80502.6608897079], [1777953641908, 80862.32986289714], [1777957216870, 80879.64169767959], [1777960831571, 80964.32892911187], [1777964458056, 80929.42691227201], [1777968059885, 80832.01520950334], [1777971629966, 80777.53289851543], [1777975269759, 80559.87773983457], [1777978810508, 80807.32656323555], [1777982450660, 80980.88740291572], [1777986059256, 81269.26250467004], [1777989674421, 81344.9530195381], [1777993211258, 81320.6271467758], [1777996849284, 81531.44168217648], [1778000429851, 81239.08701427226], [1778004027681, 81263.69235345974], [1778007641471, 81505.5389396501], [1778011242936, 81610.0981394073], [1778014849608, 81640.76606774832], [1778018415009, 81435.04217472997], [1778022048759, 81102.49055562499], [1778025642626, 80925.09365495079], [1778029246577, 81025.08656540702], [1778032811267, 81397.411569984], [1778036422686, 81358.38548975713], [1778040016151, 81584.74166306602], [1778043630236, 81306.10012559843], [1778047253578, 81297.72330722761], [1778050834724, 81473.56659293742], [1778054436137, 81329.1136388315], [1778058036661, 81899.30243968488], [1778061612605, 81952.1101049097], [1778065257616, 82290.68407538498], [1778068855127, 82496.20820745183], [1778072407183, 82205.60200195608], [1778076044107, 81706.995476948], [1778079641537, 81514.56522213451], [1778083250319, 81680.52689781821], [1778086844518, 81633.84574005251], [1778090478590, 81442.95333192401], [1778094050023, 81360.03801766584], [1778097640265, 81467.38228080935], [1778101235035, 81396.90859345869], [1778104833775, 81535.56051187172], [1778108430621, 81341.72824280302], [1778112043677, 81424.99515650333], [1778115651201, 81025.86984340467], [1778119221779, 81164.7659265684], [1778122847617, 81101.16003173548], [1778126426688, 80866.42753547305], [1778130041167, 80953.3833159498], [1778133629501, 81039.78989761735], [1778137246447, 81397.13070774359], [1778140827111, 81497.72906865228], [1778144450018, 81212.97643770608], [1778148066904, 80923.64105632599], [1778151629356, 80829.48845781687], [1778155206855, 80858.04643663602], [1778158855622, 81158.02618621176], [1778162410793, 80518.08550605948], [1778166062945, 80160.46228405276], [1778169627776, 79895.48468462411], [1778173271652, 79785.58492155476], [1778176836783, 80080.24103755607], [1778180458078, 80208.20259981617], [1778184004248, 80086.82987664758], [1778187652509, 79864.24334933555], [1778191251762, 79778.9710136237], [1778194855585, 79903.13315729475], [1778198405244, 80022.04125006415], [1778202073615, 79773.77281488809], [1778205637934, 79726.5063910817], [1778209228351, 79467.2776985759], [1778212814084, 79565.88415271358], [1778216438884, 79643.43510935546], [1778220035144, 79621.66883251265], [1778223635816, 79482.76287784053], [1778227207120, 79666.44198815993], [1778230843846, 79901.01949747415], [1778234435344, 79852.08374240961], [1778238040409, 80195.29628009013], [1778241650450, 80218.69695879071], [1778245257951, 80047.65873791873], [1778248852100, 79588.23885692912], [1778252428461, 80097.30821841754], [1778256055356, 80104.66044328224], [1778259643496, 79799.24748348113], [1778263253315, 80026.20541110853], [1778266824329, 80134.6910565651], [1778270438222, 80095.51493127189], [1778274035999, 80115.99080461846], [1778277639322, 80222.98937217446], [1778281241591, 80272.10755156755], [1778284830511, 80189.06503567853], [1778288472532, 80227.05117840739], [1778292056529, 80338.74262095778], [1778295606027, 80403.26336788909], [1778299229958, 80381.29773964443], [1778302860807, 80374.19698015944], [1778306455441, 80384.38574538061], [1778310034180, 80225.08553906319], [1778313620685, 80217.38206877769], [1778317210776, 80393.63767911753], [1778320817112, 80205.7613054906], [1778324464837, 80252.18834131895], [1778328023893, 80350.36116385079], [1778331629436, 80385.0903436548], [1778335255965, 80375.02812868063], [1778338828716, 80321.08226008785], [1778342439151, 80513.2583951042], [1778346011378, 80630.9162025437], [1778349673657, 80785.86258160052], [1778353241248, 80879.961

In [10]:
print(bitcoin_data["prices"])

[[1776348031437, 73705.01360985098], [1776351628941, 73938.04397589041], [1776355218900, 74740.25080601992], [1776358848233, 74214.42990809566], [1776362426081, 74273.00358424732], [1776366040853, 75017.42674367223], [1776369623094, 75389.68135904678], [1776373242253, 75240.31590673576], [1776376827315, 74944.91566812144], [1776380458176, 74883.21300083205], [1776384030955, 75149.1930221427], [1776387653697, 74977.75409490333], [1776391222764, 74787.851905865], [1776394807573, 74695.48255658832], [1776398432051, 74649.52985426539], [1776402060216, 74792.21540789708], [1776405653685, 74666.08972542649], [1776409248343, 74913.00922361523], [1776412817378, 75044.90134871528], [1776416471858, 75739.35058143485], [1776420035344, 75797.67899200699], [1776423613677, 75297.00919396247], [1776427227085, 75589.10032806055], [1776430804590, 76213.45555656118], [1776434480758, 77361.36237765808], [1776438058285, 77956.91427499668], [1776441669527, 77828.185699857], [1776445275036, 77862.89905005145], [1776448831603, 77498.81630549654], [1776452452485, 77164.03670386429], [1776456054342, 77436.59527540709], [1776459640617, 77362.87288021417], [1776463262842, 77496.71066229149], [1776466869578, 77308.43885337995], [1776470415387, 77128.44334858148], [1776474028704, 77169.64712633878], [1776477612377, 77201.78314338902], [1776481253738, 77315.4096324451], [1776484838295, 77013.53238285403], [1776488451751, 77158.48113774008], [1776492024127, 77152.68049883858], [1776495636584, 77131.3006381946], [1776499225517, 76998.06796704927], [1776502839772, 76755.0998125113], [1776506408049, 76617.80623429554], [1776510045450, 76188.45755869409], [1776513657316, 76072.68979550186], [1776517263736, 76224.9598173141], [1776520825301, 76137.19860160364], [1776524426751, 76251.58670751007], [1776528012360, 76181.98651177097], [1776531647226, 75927.57132288165], [1776535253230, 75864.95221180288], [1776538809275, 75653.54136303878], [1776542456722, 75670.66377392902], [1776546030982, 75757.95160113281], [1776549620269, 75828.32687513834], [1776553247003, 75830.19171188552], [1776556819243, 75728.45681761758], [1776560455762, 75652.21984514158], [1776564038652, 75642.12663561944], [1776567677341, 75558.77945979389], [1776571274063, 75540.50887836353], [1776574835911, 75681.49533537882], [1776578435261, 75569.83917977821], [1776582067182, 75407.80704076507], [1776585633524, 75295.98459973742], [1776589204218, 75244.24719211207], [1776592859248, 75020.97270538584], [1776596455940, 75236.36654292562], [1776600037294, 75599.26577131222], [1776603641851, 75624.6529610848], [1776607228888, 75920.89178630568], [1776610803231, 76024.76202757412], [1776614420279, 75840.65451654213], [1776618018075, 75495.36817299578], [1776621636729, 74800.94102146984], [1776625255283, 74795.1465182244], [1776628843659, 74974.34476516958], [1776632446413, 74689.24400809643], [1776636018388, 74460.14184607656], [1776639679302, 74137.21873636951], [1776643248126, 73856.05501487634], [1776646850777, 74346.05375810764], [1776650444180, 74623.05265769569], [1776654004643, 74458.21813860718], [1776657622245, 74653.54610763465], [1776661238550, 74581.28237935815], [1776664852141, 74277.51462154883], [1776668432318, 74789.56984853405], [1776672052000, 74795.97600729625], [1776675613386, 74741.97729093608], [1776679246167, 75062.12403807922], [1776682847491, 75045.02524645194], [1776686430682, 75179.56431310959], [1776690046403, 75285.69738107114], [1776693621627, 75290.96918392694], [1776697264999, 75004.42275652137], [1776700811000, 75687.721421251], [1776704431977, 75340.28666497084], [1776708026267, 75921.15197965335], [1776711659005, 76437.62877231697], [1776715240654, 76314.88533036472], [1776718882441, 76302.84677235561], [1776722442504, 75970.00268011336], [1776726009650, 75992.70086029985], [1776729634491, 75874.54629352967], [1776733242456, 76085.88237404238], [1776736856297, 75921.29817954023], [1776740455464, 75628.03723799669], [1776744058013, 75728.13586903199], [1776747632588, 75814.67217221636], [1776751272730, 75832.33172653822], [1776754841651, 76008.88286643253], [1776758435784, 76125.0717533993], [1776762008063, 76542.40965523037], [1776765649642, 76367.38771266557], [1776769225300, 76784.39417696862], [1776772813537, 76479.91862901945], [1776776460137, 75992.30702339568], [1776780036415, 75911.10361927166], [1776783616380, 75762.711638902], [1776787226659, 75803.94428247478], [1776790847102, 75861.34549918868], [1776794477084, 75556.47668629252], [1776798040192, 75598.61267682334], [1776801652473, 74995.37782854948], [1776805241688, 75763.05667180788], [1776808832686, 75574.10377442642], [1776812427372, 75629.08968346077], [1776816037205, 76350.25202878818], [1776819623839, 76308.7293299303], [1776823255707, 76322.61641898053], [1776826854527, 77536.75470746626], [1776830440948, 77587.83202645402], [1776834047209, 77478.20552898936], [1776837657207, 78016.40224612548], [1776841210741, 77988.76554637455], [1776844851547, 78067.63707556471], [1776848457778, 78058.08975780573], [1776852056646, 78024.52473191661], [1776855646807, 78144.37988534916], [1776859256988, 78287.86829838748], [1776862800597, 78273.8966848666], [1776866403201, 78815.99780735128], [1776870016489, 79080.63292286295], [1776873664024, 79321.15968354288], [1776877225757, 78751.70323522005], [1776880850652, 78923.92967916405], [1776884435409, 79026.34137679906], [1776888052843, 78946.3912548935], [1776891652677, 78453.79426420951], [1776895205923, 78791.52632630398], [1776898843763, 78602.89731358779], [1776902440823, 78194.78334884858], [1776906048116, 78406.2930435807], [1776909618441, 78357.18396749758], [1776913247770, 77985.92377137982], [1776916847486, 77745.85432228484], [1776920422561, 77935.74125864716], [1776924037500, 78027.34427996507], [1776927617638, 78224.5180282668], [1776931239673, 78031.99538001728], [1776934824199, 77897.87177343022], [1776938453511, 77638.50183036197], [1776942013367, 77421.70696946804], [1776945660400, 77720.82903527566], [1776949200958, 77689.20240973093], [1776952803966, 77534.60343866517], [1776956461571, 78194.45325685579], [1776960035533, 78400.43360010415], [1776963672798, 78107.69300312691], [1776967235961, 77774.75239415659], [1776970841386, 77788.60996280434], [1776974471601, 77758.18784079723], [1776978071533, 77892.40295122238], [1776981652886, 77960.96780301731], [1776985243134, 78241.97434139495], [1776988855292, 78260.61998045091], [1776992429654, 78385.9994566751], [1776996008427, 78450.36540019314], [1776999647663, 78147.75938482724], [1777003251454, 77747.45626454431], [1777006841879, 77705.47025945061], [1777010430510, 77986.53527373911], [1777014051674, 77820.67157019368], [1777017652384, 77631.4765633673], [1777021250209, 77849.7374088029], [1777024808376, 77541.44001609184], [1777028457707, 77769.18978227278], [1777032048030, 78246.79964995776], [1777035660411, 78191.33520155153], [1777039244185, 78079.14695903476], [1777042836375, 78040.02364193133], [1777046444329, 78047.3380693329], [1777050031162, 77754.58226000571], [1777053646647, 77684.72881988292], [1777057205954, 77597.78722462713], [1777060822681, 77640.62590796669], [1777064428860, 77743.96821879945], [1777068076897, 77598.4707273492], [1777071651647, 77360.7247577714], [1777075232951, 77444.79563692068], [1777078840202, 77462.08912922682], [1777082455350, 77566.91332664572], [1777086070721, 77632.1049866153], [1777089671228, 77659.99727324375], [1777093226002, 77641.01117283583], [1777096804040, 77526.33855221451], [1777100461155, 77546.29139125944], [1777104027315, 77552.43014091096], [1777107657268, 77633.44423479457], [1777111256854, 77756.29359070981], [1777114849067, 77798.77053029239], [1777118449060, 77681.05139222337], [1777122035344, 77572.56576897178], [1777125659933, 77704.47912526024], [1777129265720, 77666.8630936243], [1777132836546, 77369.37427037527], [1777136412416, 77411.63283414992], [1777140028307, 77268.59468461889], [1777143647539, 77327.62457986774], [1777147231506, 77334.26544839946], [1777150812443, 77485.94368156035], [1777154433526, 77517.55017621993], [1777158026584, 77571.92469081761], [1777161643793, 77619.14219872655], [1777165225674, 77504.17855812809], [1777168803806, 77474.23663746598], [1777172445470, 77508.39871110146], [1777176012276, 77421.9680597692], [1777179641556, 77780.732585964], [1777183239567, 78011.43215971511], [1777186801656, 77968.04637604058], [1777190448885, 78104.00311325732], [1777194025361, 78046.40161728268], [1777197648136, 78007.27442207371], [1777201242207, 78005.02861473465], [1777204814977, 78110.88161863454], [1777208439504, 77838.15248676843], [1777212052097, 77940.84317164119], [1777215657502, 78104.22069639667], [1777219243334, 78050.75607592058], [1777222856563, 77985.65557780031], [1777226428642, 78034.51980737594], [1777230043789, 78274.34065021528], [1777233625299, 78240.93686631313], [1777237256720, 78229.8417681944], [1777240803843, 78407.16125498862], [1777244420641, 78378.05061328351], [1777248027238, 78645.12560170851], [1777251649775, 79260.26248669959], [1777255224503, 79217.03669448356], [1777258812333, 79161.16903469128], [1777262460515, 79096.32338375495], [1777266008318, 78918.2674998158], [1777269633628, 77819.8190965596], [1777273211988, 77728.11296302704], [1777276835326, 77653.42820403715], [1777280423824, 77801.48133620767], [1777284009832, 77918.22130374532], [1777287648733, 77858.06178429707], [1777291258779, 77839.13057125034], [1777294832811, 77636.7357570139], [1777298420954, 77767.52764704514], [1777302065894, 77816.0572264602], [1777305613302, 76772.56122738226], [1777309212461, 76597.37629170864], [1777312851604, 76701.61237959677], [1777316456805, 76840.12034837836], [1777320031438, 76829.48158520267], [1777323648838, 76986.58306724002], [1777327246196, 76798.22801186582], [1777330843889, 77068.29246494433], [1777334441441, 77361.29911038803], [1777338046510, 77383.54057877463], [1777341604023, 77090.31107128707], [1777345256701, 76833.05668971647], [1777348824854, 76804.77382356762], [1777352448493, 76884.15413049556], [1777356041954, 76948.09017415001], [1777359628376, 76711.2208351938], [1777363239870, 76871.94798938799], [1777366857917, 76823.96703050246], [1777370432750, 76582.2382436488], [1777374077572, 76587.46607990249], [1777377641615, 76182.61040738711], [1777381251576, 76342.5588428331], [1777384839320, 76180.39793452619], [1777388463316, 75849.31178726906], [1777392056195, 76040.86480284185], [1777395634217, 76108.79943793108], [1777399253791, 76174.499991253], [1777402876832, 76223.05617004436], [1777406476570, 76340.1341246333], [1777410076527, 76445.86122627115], [1777413677983, 76353.70892706158], [1777417275820, 76229.4038502392], [1777420879320, 76345.22521002527], [1777424477903, 76505.05470800745], [1777428056205, 76537.83594119303], [1777431667974, 76478.80195313173], [1777435222141, 76961.46963288501], [1777438802625, 77289.79308700348], [1777442438633, 77258.63042398472], [1777446031012, 76964.99741594712], [1777449611567, 77023.71023600476], [1777453259060, 77028.46347185198], [1777456873258, 77629.86690905425], [1777460469390, 77596.56363815261], [1777464054224, 77579.59487006326], [1777467638082, 77127.99638212805], [1777471262001, 76776.12526378022], [1777474843812, 76558.49021649477], [1777478461713, 75858.12862387307], [1777482054287, 75763.67004036404], [1777485628569, 75996.93512732009], [1777489255543, 75436.56581067356], [1777492847135, 75468.90041834336], [1777496409185, 75701.80458172278], [1777500034074, 75924.91798195371], [1777503640535, 75907.29950981027], [1777507246340, 75774.8855230121], [1777510821235, 76255.01364165342], [1777514424298, 76220.83380666314], [1777518017943, 75691.65564515392], [1777521641929, 75909.7088552133], [1777525238275, 75459.6526551717], [1777528838043, 75580.06196734082], [1777532451783, 75713.26283708648], [1777536059565, 76085.14106760567], [1777539634276, 76026.7764354485], [1777543243024, 76090.4726987875], [1777546848342, 75986.04492329038], [1777550421241, 76005.83880555014], [1777554064561, 76280.05036510443], [1777557650826, 76410.61364346408], [1777561229633, 76270.43468783535], [1777564859951, 76455.76704590907], [1777568448747, 76216.33823270486], [1777572024638, 76235.32221878375], [1777575642712, 76343.14131925348], [1777579239482, 76391.95833110265], [1777582850514, 76465.47268894286], [1777586444363, 76231.26886058506], [1777590011796, 76189.37205616337], [1777593600693, 76286.57710950871], [1777597253489, 76379.67128631244], [1777600847284, 76656.57064385938], [1777604401370, 76517.3133818177], [1777608010968, 77085.22718465359], [1777611622505, 77009.0736401404], [1777615238361, 77118.9788591889], [1777618840828, 77034.26419331781], [1777622426705, 77096.21079038092], [1777626021323, 77340.98047049128], [1777629616743, 77231.30471966216], [1777633254545, 77240.15798301293], [1777636845526, 77433.64205650402], [1777640442692, 77969.27491618901], [1777644070071, 78695.21355815475], [1777647613191, 78320.42975742156], [1777651249972, 78434.82448589527], [1777654803247, 78252.9324694872], [1777658452001, 78548.40091164663], [1777662031370, 78382.96178450093], [1777665628062, 78423.58948035864], [1777669239242, 77859.3116606549], [1777672849543, 78174.02675323762], [1777676456057, 78138.26976073837], [1777680033537, 78172.07422147921], [1777683636113, 78308.37520882013], [1777687244908, 78286.27861903312], [1777690811975, 78362.29923426916], [1777694439668, 78437.93476926665], [1777698006749, 78150.11936951149], [1777701628993, 78195.68680702572], [1777705245701, 78306.93283732959], [1777708848392, 78194.06055081423], [1777712440845, 78285.70832684374], [1777716047319, 78281.28398457692], [1777719647841, 78240.11769161666], [1777723241480, 78128.46024348195], [1777726852674, 78193.2744831238], [1777730423002, 78360.21898348848], [1777734057596, 78411.38510755789], [1777737633180, 78461.63721855872], [1777741211069, 78435.08617699439], [1777744804005, 78382.70991118148], [1777748446535, 78457.5389191646], [1777752015067, 78447.53632340279], [1777755647472, 78439.4139272263], [1777759224789, 78732.6338722369], [1777762835245, 78804.99536374844], [1777766459728, 78666.02056290468], [1777770056603, 78525.2146039029], [1777773628483, 78247.12211102132], [1777777266475, 78157.88034742486], [1777780854226, 78188.40860775959], [1777784457318, 78146.92223825728], [1777788049289, 78229.08291869442], [1777791668417, 78271.08132011641], [1777795238248, 78350.69027764065], [1777798857190, 78386.58845756314], [1777802456075, 78514.79652456472], [1777806033462, 78393.61348590766], [1777809611955, 78651.90783179233], [1777813228703, 78723.62272234702], [1777816856232, 78671.01722577176], [1777820425426, 78735.77368245517], [1777824001209, 78648.51670661499], [1777827643040, 78671.22481306917], [1777831264652, 78714.14816000318], [1777834829236, 78723.71597574794], [1777838406341, 78772.93638758908], [1777842024969, 78882.41352644576], [1777845602579, 78784.56538231378], [1777849218129, 79164.91262664807], [1777852824199, 78542.80803714818], [1777856421733, 78523.09209511426], [1777860011798, 79525.0486011737], [1777863647107, 80247.57433910447], [1777867219152, 80254.0760312916], [1777870804028, 80296.72362760552], [1777874449287, 80010.78689175253], [1777878026455, 79920.44749612657], [1777881653151, 79689.3122143952], [1777885252207, 79714.0128258611], [1777888851475, 79832.33782372707], [1777892430233, 78911.17072497762], [1777896029630, 78794.5386775698], [1777899646426, 78946.74382793218], [1777903219620, 78795.3827203887], [1777906826294, 80262.81441266934], [1777910459053, 79961.47965724225], [1777914029774, 79997.7587206583], [1777917624474, 80468.0775179202], [1777921225417, 80114.39169381397], [1777924836109, 80052.0708073038], [1777928449527, 79929.45608891523], [1777932046495, 80248.55770465586], [1777935654225, 80060.10705547684], [1777939220337, 79824.40331204748], [1777942842625, 80138.68119208484], [1777946436397, 80325.98978821686], [1777950042948, 80502.6608897079], [1777953641908, 80862.32986289714], [1777957216870, 80879.64169767959], [1777960831571, 80964.32892911187], [1777964458056, 80929.42691227201], [1777968059885, 80832.01520950334], [1777971629966, 80777.53289851543], [1777975269759, 80559.87773983457], [1777978810508, 80807.32656323555], [1777982450660, 80980.88740291572], [1777986059256, 81269.26250467004], [1777989674421, 81344.9530195381], [1777993211258, 81320.6271467758], [1777996849284, 81531.44168217648], [1778000429851, 81239.08701427226], [1778004027681, 81263.69235345974], [1778007641471, 81505.5389396501], [1778011242936, 81610.0981394073], [1778014849608, 81640.76606774832], [1778018415009, 81435.04217472997], [1778022048759, 81102.49055562499], [1778025642626, 80925.09365495079], [1778029246577, 81025.08656540702], [1778032811267, 81397.411569984], [1778036422686, 81358.38548975713], [1778040016151, 81584.74166306602], [1778043630236, 81306.10012559843], [1778047253578, 81297.72330722761], [1778050834724, 81473.56659293742], [1778054436137, 81329.1136388315], [1778058036661, 81899.30243968488], [1778061612605, 81952.1101049097], [1778065257616, 82290.68407538498], [1778068855127, 82496.20820745183], [1778072407183, 82205.60200195608], [1778076044107, 81706.995476948], [1778079641537, 81514.56522213451], [1778083250319, 81680.52689781821], [1778086844518, 81633.84574005251], [1778090478590, 81442.95333192401], [1778094050023, 81360.03801766584], [1778097640265, 81467.38228080935], [1778101235035, 81396.90859345869], [1778104833775, 81535.56051187172], [1778108430621, 81341.72824280302], [1778112043677, 81424.99515650333], [1778115651201, 81025.86984340467], [1778119221779, 81164.7659265684], [1778122847617, 81101.16003173548], [1778126426688, 80866.42753547305], [1778130041167, 80953.3833159498], [1778133629501, 81039.78989761735], [1778137246447, 81397.13070774359], [1778140827111, 81497.72906865228], [1778144450018, 81212.97643770608], [1778148066904, 80923.64105632599], [1778151629356, 80829.48845781687], [1778155206855, 80858.04643663602], [1778158855622, 81158.02618621176], [1778162410793, 80518.08550605948], [1778166062945, 80160.46228405276], [1778169627776, 79895.48468462411], [1778173271652, 79785.58492155476], [1778176836783, 80080.24103755607], [1778180458078, 80208.20259981617], [1778184004248, 80086.82987664758], [1778187652509, 79864.24334933555], [1778191251762, 79778.9710136237], [1778194855585, 79903.13315729475], [1778198405244, 80022.04125006415], [1778202073615, 79773.77281488809], [1778205637934, 79726.5063910817], [1778209228351, 79467.2776985759], [1778212814084, 79565.88415271358], [1778216438884, 79643.43510935546], [1778220035144, 79621.66883251265], [1778223635816, 79482.76287784053], [1778227207120, 79666.44198815993], [1778230843846, 79901.01949747415], [1778234435344, 79852.08374240961], [1778238040409, 80195.29628009013], [1778241650450, 80218.69695879071], [1778245257951, 80047.65873791873], [1778248852100, 79588.23885692912], [1778252428461, 80097.30821841754], [1778256055356, 80104.66044328224], [1778259643496, 79799.24748348113], [1778263253315, 80026.20541110853], [1778266824329, 80134.6910565651], [1778270438222, 80095.51493127189], [1778274035999, 80115.99080461846], [1778277639322, 80222.98937217446], [1778281241591, 80272.10755156755], [1778284830511, 80189.06503567853], [1778288472532, 80227.05117840739], [1778292056529, 80338.74262095778], [1778295606027, 80403.26336788909], [1778299229958, 80381.29773964443], [1778302860807, 80374.19698015944], [1778306455441, 80384.38574538061], [1778310034180, 80225.08553906319], [1778313620685, 80217.38206877769], [1778317210776, 80393.63767911753], [1778320817112, 80205.7613054906], [1778324464837, 80252.18834131895], [1778328023893, 80350.36116385079], [1778331629436, 80385.0903436548], [1778335255965, 80375.02812868063], [1778338828716, 80321.08226008785], [1778342439151, 80513.2583951042], [1778346011378, 80630.9162025437], [1778349673657, 80785.86258160052], [1778353241248, 80879.96174929348], 

In [14]:
import pandas as pd
data=pd.DataFrame(bitcoin_data["prices"],columns=["TimeStamp","Price"])
print(data)

         TimeStamp         Price
0    1776348031437  73705.013610
1    1776351628941  73938.043976
2    1776355218900  74740.250806
3    1776358848233  74214.429908
4    1776362426081  74273.003584
..             ...           ...
716  1778925660182  78054.510708
717  1778929233785  77912.516783
718  1778932840423  78051.937282
719  1778936425024  77982.286288
720  1778941363000  77897.346868

[721 rows x 2 columns]

In [17]:
data["Date"]=pd.to_datetime(data["TimeStamp"],unit="ms")
print(data["Date"])

0     2026-04-16 14:00:31.437
1     2026-04-16 15:00:28.941
2     2026-04-16 16:00:18.900
3     2026-04-16 17:00:48.233
4     2026-04-16 18:00:26.081
                ...
716   2026-05-16 10:01:00.182
717   2026-05-16 11:00:33.785
718   2026-05-16 12:00:40.423
719   2026-05-16 13:00:25.024
720   2026-05-16 14:22:43.000
Name: Date, Length: 721, dtype: datetime64[ms]

In [18]:
data["Date"].head()

0   2026-04-16 14:00:31.437
1   2026-04-16 15:00:28.941
2   2026-04-16 16:00:18.900
3   2026-04-16 17:00:48.233
4   2026-04-16 18:00:26.081
Name: Date, dtype: datetime64[ms]

In [20]:
candlestick_data=data.groupby(data.Date.dt.date).agg({"Price":["min","max","first","last"]})
print(candlestick_data)

                   Price
                     min           max         first          last
Date
2026-04-16  73705.013610  75389.681359  73705.013610  74883.213001
2026-04-17  74649.529854  77956.914275  75149.193022  77308.438853
2026-04-18  75653.541363  77315.409632  77128.443349  75830.191712
2026-04-19  74137.218736  76024.762028  75728.456818  74137.218736
2026-04-20  73856.055015  76437.628772  73856.055015  75992.700860
2026-04-21  74995.377829  76784.394177  75874.546294  75629.089683
2026-04-22  76308.729330  79321.159684  76350.252029  78602.897314
2026-04-23  77421.706969  78406.293044  78194.783349  78241.974341
2026-04-24  77360.724758  78450.365400  78260.619980  77360.724758
2026-04-25  77268.594685  77798.770530  77444.795637  77571.924691
2026-04-26  77421.968060  78407.161255  77619.142199  78378.050613
2026-04-27  76597.376292  79260.262487  78645.125602  77068.292465
2026-04-28  75849.311787  77383.540579  77361.299110  76229.403850
2026-04-29  75436.565811  77629.866909  76345.225210  75907.299510
2026-04-30  75459.652655  76465.472689  75774.885523  76189.372056
2026-05-01  76286.577110  78695.213558  76286.577110  78138.269761
2026-05-02  78128.460243  78804.995364  78172.074221  78804.995364
2026-05-03  78146.922238  79164.912627  78666.020563  79164.912627
2026-05-04  78523.092095  80468.077518  78542.808037  80060.107055
2026-05-05  79824.403312  81640.766068  79824.403312  81102.490556
2026-05-06  80925.093655  82496.208207  80925.093655  81341.728243
2026-05-07  79778.971014  81497.729069  81424.995157  79903.133157
2026-05-08  79467.277699  80272.107552  80022.041250  80272.107552
2026-05-09  80189.065036  80894.730129  80189.065036  80742.816774
2026-05-10  80636.174386  82025.589323  80678.033943  82025.589323
2026-05-11  80694.979325  82145.656068  82145.656068  81823.286175
2026-05-12  79962.923884  81725.207717  81725.207717  80652.284345
2026-05-13  78827.547922  81234.864127  80480.886001  79401.913320
2026-05-14  78973.186317  81700.160591  79277.804518  81418.220209
2026-05-15  78742.811979  81487.622792  81051.982888  79067.663781
2026-05-16  77897.346868  79124.943246  79071.540267  77897.346868

In [22]:
candlestick_data.head()

                   Price
                     min           max         first          last
Date
2026-04-16  73705.013610  75389.681359  73705.013610  74883.213001
2026-04-17  74649.529854  77956.914275  75149.193022  77308.438853
2026-04-18  75653.541363  77315.409632  77128.443349  75830.191712
2026-04-19  74137.218736  76024.762028  75728.456818  74137.218736
2026-04-20  73856.055015  76437.628772  73856.055015  75992.700860

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dict_={"a":[11,21,31],"b":[12,22,32]}
df=pd.DataFrame(dict_)
type(df)

pandas.DataFrame

In [4]:
df.head()

    a   b
0  11  12
1  21  22
2  31  32

In [5]:
df.mean()

a    21.0
b    22.0
dtype: float64

### REST APIs
Rest APIs function by sending a request, the request is communicated via HTTP message. The HTTP message usually contains a JSON file. This contains instructions for what operation we would like the service or resource to perform. In a similar manner, API returns a response, via an HTTP message, this response is usually contained within a JSON.

### NBA API

In [6]:
!pip install nba_api

Collecting nba_api
  Downloading nba_api-1.11.4-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from nba_api) (2.4.4)
Requirement already satisfied: pandas>=2.1.0 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from nba_api) (3.0.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from nba_api) (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from pandas>=2.1.0->nba_api) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=2.1.0->nba_api) (1.17.0)
Downloading nba_api-1.11.4-py3-none-any.whl (322 kB)
Installing collected packages: nba_api
Successfully installed nba_api-1.11.4

In [21]:
from nba_api.stats.static import teams

In [25]:
def one_dict(list_dict):
    keys=list_dict[0].keys()
    out_dict={key:[] for key in keys}
    for dict_ in list_dict:
        for key,value in dict_.items():
            out_dict[key].append(value)
    return out_dict

In [26]:
nba_teams=teams.get_teams()
nba_teams[0:]

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Georgia',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970},
 {'id': 1610612740,
  'full_name': 'New Orleans Pelicans',
  'abbreviation': 'NOP',
  'nickname': 'Pelicans',
  'city': 'New Orleans',
  'state': 'Louisiana',
  'year_founded': 2002},
 {'id': 1610612741,
  'full_name': 'Chicago Bulls',
  'abbreviation': 'CHI',
  'nickname': 'Bulls',
  'city': 'Chicago',
  'state': 'Illinois',
  'year_founded': 1966},
 {'id': 1610612742,
  'full_name': 'Dallas Mavericks',
  'abbreviation': 'DAL',
  'nickname': 'Mavericks',
  'city': 'Dallas',
  'state': 'Texas',
  'year_founded': 1980},
 {'id': 1610612743,
  'full_name': 'Denver Nuggets',
  'abbreviation': 'DEN',
  'nickname': 'Nuggets',
  'city': 'Denver',
  'state': 'Colorado',
  'year_founded': 1976},
 {'id': 1610612744,
  'full_name': 'Golden State Warriors',
  'abbreviation': 'GSW',
  'nickname': 'Warriors',
  'city': 'San Francisco',
  'state': 'California',
  'year_founded': 1946},
 {'id': 1610612745,
  'full_name': 'Houston Rockets',
  'abbreviation': 'HOU',
  'nickname': 'Rockets',
  'city': 'Houston',
  'state': 'Texas',
  'year_founded': 1967},
 {'id': 1610612746,
  'full_name': 'Los Angeles Clippers',
  'abbreviation': 'LAC',
  'nickname': 'Clippers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1970},
 {'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612748,
  'full_name': 'Miami Heat',
  'abbreviation': 'MIA',
  'nickname': 'Heat',
  'city': 'Miami',
  'state': 'Florida',
  'year_founded': 1988},
 {'id': 1610612749,
  'full_name': 'Milwaukee Bucks',
  'abbreviation': 'MIL',
  'nickname': 'Bucks',
  'city': 'Milwaukee',
  'state': 'Wisconsin',
  'year_founded': 1968},
 {'id': 1610612750,
  'full_name': 'Minnesota Timberwolves',
  'abbreviation': 'MIN',
  'nickname': 'Timberwolves',
  'city': 'Minnesota',
  'state': 'Minnesota',
  'year_founded': 1989},
 {'id': 1610612751,
  'full_name': 'Brooklyn Nets',
  'abbreviation': 'BKN',
  'nickname': 'Nets',
  'city': 'Brooklyn',
  'state': 'New York',
  'year_founded': 1976},
 {'id': 1610612752,
  'full_name': 'New York Knicks',
  'abbreviation': 'NYK',
  'nickname': 'Knicks',
  'city': 'New York',
  'state': 'New York',
  'year_founded': 1946},
 {'id': 1610612753,
  'full_name': 'Orlando Magic',
  'abbreviation': 'ORL',
  'nickname': 'Magic',
  'city': 'Orlando',
  'state': 'Florida',
  'year_founded': 1989},
 {'id': 1610612754,
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND',
  'nickname': 'Pacers',
  'city': 'Indiana',
  'state': 'Indiana',
  'year_founded': 1976},
 {'id': 1610612755,
  'full_name': 'Philadelphia 76ers',
  'abbreviation': 'PHI',
  'nickname': '76ers',
  'city': 'Philadelphia',
  'state': 'Pennsylvania',
  'year_founded': 1949},
 {'id': 1610612756,
  'full_name': 'Phoenix Suns',
  'abbreviation': 'PHX',
  'nickname': 'Suns',
  'city': 'Phoenix',
  'state': 'Arizona',
  'year_founded': 1968},
 {'id': 1610612757,
  'full_name': 'Portland Trail Blazers',
  'abbreviation': 'POR',
  'nickname': 'Trail Blazers',
  'city': 'Portland',
  'state': 'Oregon',
  'year_founded': 1970},
 {'id': 1610612758,
  'full_name': 'Sacramento Kings',
  'abbreviation': 'SAC',
  'nickname': 'Kings',
  'city': 'Sacramento',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612759,
  'full_name': 'San Antonio Spurs',
  'abbreviation': 'SAS',
  'nickname': 'Spurs',
  'city': 'San Antonio',
  'state': 'Texas',
  'year_founded': 1976},
 {'id': 1610612760,
  'full_name': 'Oklahoma City Thunder',
  'abbreviation': 'OKC',
  'nickname': 'Thunder',
  'city': 'Oklahoma City',
  'state': 'Oklahoma',
  'year_founded': 1967},
 {'id': 1610612761,
  'full_name': 'Toronto Raptors',
  'abbreviation': 'TOR',
  'nickname': 'Raptors',
  'city': 'Toronto',
  'state': 'Ontario',
  'year_founded': 1995},
 {'id': 1610612762,
  'full_name': 'Utah Jazz',
  'abbreviation': 'UTA',
  'nickname': 'Jazz',
  'city': 'Utah',
  'state': 'Utah',
  'year_founded': 1974},
 {'id': 1610612763,
  'full_name': 'Memphis Grizzlies',
  'abbreviation': 'MEM',
  'nickname': 'Grizzlies',
  'city': 'Memphis',
  'state': 'Tennessee',
  'year_founded': 1995},
 {'id': 1610612764,
  'full_name': 'Washington Wizards',
  'abbreviation': 'WAS',
  'nickname': 'Wizards',
  'city': 'Washington',
  'state': 'District of Columbia',
  'year_founded': 1961},
 {'id': 1610612765,
  'full_name': 'Detroit Pistons',
  'abbreviation': 'DET',
  'nickname': 'Pistons',
  'city': 'Detroit',
  'state': 'Michigan',
  'year_founded': 1948},
 {'id': 1610612766,
  'full_name': 'Charlotte Hornets',
  'abbreviation': 'CHA',
  'nickname': 'Hornets',
  'city': 'Charlotte',
  'state': 'North Carolina',
  'year_founded': 1988}]

dict_nba_team=one_dict(nba_teams)
df_teams=pd.DataFrame(dict_nba_team)
df_teams.head()

In [32]:
df_warriors=df_teams[df_teams["nickname"]]="Warriors"
df_warriors

'Warriors'

### Requests

In [15]:
import requests
url="https://www.ibm.com/"
r=requests.get(url)
r.status_code
header=r.headers
print(header["date"])
print(header["Content-Type"])
print(r.encoding)
print(r.text[0:100])

Fri, 22 May 2026 06:39:59 GMT
text/html;charset=utf-8
utf-8

<!DOCTYPE HTML>

<html lang="en">
<head>

### GET Request

In [22]:
url_get="http://httpbin.org/get"
payload={"name":"Joseph","ID":"123"}
r=requests.get(url_get,params=payload)
r.url:"http://httpbin.org/get?name=Joseph&ID=123"
r.status_code
r.text
r.json()
r.json()["args"]

{'ID': '123', 'name': 'Joseph'}

### POST

In [25]:
url_post="http://httpbin.org/post"
payload={"name":"Joseph","ID":"123"}
r_post=requests.post(url_post,data=payload)
print("POST request URL:",r_post.url)
print("GET request URL:",r.url)

POST request URL: http://httpbin.org/post
GET request URL: http://httpbin.org/get?name=Joseph&ID=123

### Web Scrapping

In [26]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from beautifulsoup4) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install requests

Requirement already satisfied: requests in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from requests) (2026.2.25)
Note: you may need to restart the kernel to use updated packages.

In [1]:
from bs4 import BeautifulSoup
print("Beautiful Soup Installed")

import requests
print("Requests Installed")

Beautiful Soup Installed
Requests Installed

In [3]:
import requests
from bs4 import BeautifulSoup
url="https://en.wikipedia.org/wiki/IBM"
response=requests.get(url)
html_content=response.text
soup=BeautifulSoup(html_content,"html.parser")
print(html_content[:500])

Please set a user-agent and respect our robot policy https://w.wiki/4wJS. See also https://phabricator.wikimedia.org/T400119.

In [4]:
# Find all <a> tags (anchor tags) in the HTML
links=soup.find_all("a")

# Iterate through the list of links and print their text
for link in links:
    print(link.text)

### Random User And Fruityvice API Examples
RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more. More information on RandomUser can be found here.

The Fruityvice API web service which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The web service is completely free to use and contribute to.

In [5]:
!pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: randomuser
  Building wheel for randomuser (pyproject.toml) ... done
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5105 sha256=4254721af0c1363da5404a6c150a486e788e43ef0845c39f40b7dfaa6a689c18
  Stored in directory: /Users/sayamdipdeychaklader/Library/Caches/pip/wheels/fc/8d/74/bcdd5e8a9433bfa4c4f9c1cccbfec40139322a28d77f61e45e
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

### 1) RandomUser API

In [21]:
from randomuser import RandomUser
import pandas as pd

In [22]:
r=RandomUser()
some_list=r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x11a768350>,
 <randomuser.RandomUser at 0x11a7a2b10>,
 <randomuser.RandomUser at 0x11a76b150>,
 <randomuser.RandomUser at 0x11a76bfd0>,
 <randomuser.RandomUser at 0x11a76bc10>,
 <randomuser.RandomUser at 0x11a76b890>,
 <randomuser.RandomUser at 0x11a768e90>,
 <randomuser.RandomUser at 0x11a76a550>,
 <randomuser.RandomUser at 0x11a7980d0>,
 <randomuser.RandomUser at 0x11a769150>]

### Get Methods
    get_cell()
    get_city()
    get_dob()
    get_email()
    get_first_name()
    get_full_name()
    get_gender()
    get_id()
    get_id_number()
    get_id_type()
    get_info()
    get_last_name()
    get_login_md5()
    get_login_salt()
    get_login_sha1()
    get_login_sha256()
    get_nat()
    get_password()
    get_phone()
    get_picture()
    get_postcode()
    get_registered()
    get_state()
    get_street()
    get_username()
    get_zipcode()

In [23]:
#### We only need 10 users with full names and their email addresses
for user in some_list:
    print(user.get_full_name()," ",user.get_email())

Jar Ferguson   jar.ferguson@example.com
Tatiana Rezende   tatiana.rezende@example.com
Ceyhan Çevik   ceyhan.cevik@example.com
Alfred Olsen   alfred.olsen@example.com
Pinja Pesola   pinja.pesola@example.com
Lya Marchand   lya.marchand@example.com
Alexander Møller   alexander.moller@example.com
Tércio da Cruz   tercio.dacruz@example.com
Licelima Lima   licelima.lima@example.com
Heinrich Nitschke   heinrich.nitschke@example.com

In [24]:
#### generate photos of the random 10 users.
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/men/73.jpg
https://randomuser.me/api/portraits/women/54.jpg
https://randomuser.me/api/portraits/women/37.jpg
https://randomuser.me/api/portraits/men/14.jpg
https://randomuser.me/api/portraits/women/16.jpg
https://randomuser.me/api/portraits/women/4.jpg
https://randomuser.me/api/portraits/men/76.jpg
https://randomuser.me/api/portraits/men/27.jpg
https://randomuser.me/api/portraits/women/91.jpg
https://randomuser.me/api/portraits/men/50.jpg

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [27]:
def get_users():
    users=[]
    r=RandomUser()
    users1=r.generate_users(9)
    for user in users1:
        users.append({"Name":user.get_full_name(),
                      "Gender":user.get_gender(),
                      "City":user.get_city(),
                      "State":user.get_state(),
                      "Email":user.get_email(),
                      "DOB":user.get_dob(),
                      "Picture":user.get_picture()})
    return pd.DataFrame(users)

In [28]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,کیانا محمدخان,female,شهریار,زنجان,khyn.mhmdkhn@example.com,1947-08-18T19:39:37.554Z,https://randomuser.me/api/portraits/women/71.jpg
1,Nalan Saygıner,female,Kastamonu,Bilecik,nalan.sayginer@example.com,1984-03-25T09:08:11.463Z,https://randomuser.me/api/portraits/women/30.jpg
2,Adèle Riviere,female,Lyon,Paris,adele.riviere@example.com,1986-02-05T16:56:45.518Z,https://randomuser.me/api/portraits/women/59.jpg
3,Molly Robinson,female,Hastings,Auckland,molly.robinson@example.com,1984-06-01T12:32:26.930Z,https://randomuser.me/api/portraits/women/68.jpg
4,Pinja Korpi,female,Vihanti,Lapland,pinja.korpi@example.com,1995-11-29T21:50:02.843Z,https://randomuser.me/api/portraits/women/38.jpg
5,Kenneth Barrett,male,Jacksonville,Michigan,kenneth.barrett@example.com,1975-09-10T21:04:59.978Z,https://randomuser.me/api/portraits/men/17.jpg
6,Dustin Miles,male,Devonport,South Australia,dustin.miles@example.com,1961-06-15T12:43:05.373Z,https://randomuser.me/api/portraits/men/16.jpg
7,Amanda Saari,female,Kronoby,Ostrobothnia,amanda.saari@example.com,1958-08-08T05:32:35.540Z,https://randomuser.me/api/portraits/women/36.jpg
8,Neea Rautio,female,Kempele,Ostrobothnia,neea.rautio@example.com,1970-07-24T12:51:14.351Z,https://randomuser.me/api/portraits/women/36.jpg

### Example 2: Fruityvice API

In [43]:
import requests
import json

In [44]:
data=requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")
results=json.loads(data.text)

In [45]:
pd.DataFrame(results)
df=pd.json_normalize(results)
df

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

In [47]:
cal_banana=df.loc[df["name"]=="Banana"]
(cal_banana.iloc[0]["nutritions.calories"]),(cal_banana.iloc[0]["genus"])

(np.int64(96), 'Musa')

### Official Joke API

In [48]:
import requests
data=requests.get("https://official-joke-api.appspot.com/jokes/ten")
retrieve=json.loads(data.text)
pd.DataFrame(retrieve)
df=pd.json_normalize(retrieve)

In [49]:
df

,type,setup,punchline,id
0,general,What did the ocean say to the shore?,"Nothing, it just waved.",179
1,general,What do you call a cow on a trampoline?,A milk shake!,195
2,programming,Why did the functions stop calling each other?,Because they had constant arguments.,406
3,general,Did you hear about the crime in the parking ga...,It was wrong on so many levels.,394
4,general,What do you call a troublesome Canadian high s...,A poutine.,216
5,general,What did the Buffalo say to his little boy whe...,Bison.,168
6,general,Why did the worker get fired from the orange j...,Lack of concentration.,336
7,general,What do you call an Argentinian with a rubber ...,Roberto,218
8,general,What did the janitor say when he jumped out of...,Supplies!,424
9,general,What's red and bad for your teeth?,A Brick.,268