### Read CSV File

In [1]:
import pandas as pd
csv_file="./file1.csv"
df=pd.read_csv(csv_file)
df

,Resource_ID,Resource_Type,Resource_Name,Provider,Topic,Subtopic,Difficulty_Level,Duration_Hours,Prerequisites,Cost_USD,URL,Key_Skills,Certification_Available,Last_Updated,Learning_Path
0,GA001,Course,Generative AI Engineering,IBM,Fundamentals,LLM Basics,Beginner,20,NaN,0,https://www.ibm.com/generative-ai,LLM Architecture;Transformers;Prompting,Yes,2025-01,Foundation
1,GA002,Course,Google Generative AI Essentials,Google,Fundamentals,LLM Basics,Beginner,15,NaN,0,https://cloud.google.com/generative-ai,Gen AI Concepts;Google AI Tools,Yes,2025-02,Foundation
2,GA003,Course,Transformer Models and Attention,DeepLearning.AI,Architecture,Transformers,Intermediate,10,ML Fundamentals,Free,https://www.deeplearning.ai,Attention Mechanism;Self-Attention;Positional ...,No,2025-01,Architecture
3,GA004,Course,Prompt Engineering Masterclass,Andrew Ng,Techniques,Prompt Design,Beginner,8,NaN,49,https://www.deeplearning.ai/short-courses/,Few-shot Learning;Chain-of-Thought;Role Prompting,No,2025-02,Intermediate
4,GA005,Course,Fine-tuning LLMs,DeepLearning.AI,Techniques,Model Adaptation,Intermediate,6,ML Fundamentals;LLM Basics,Free,https://www.deeplearning.ai/short-courses/,PEFT;LoRA;QLoRA;Fine-tuning,No,2025-01,Advanced
5,GA006,Course,Retrieval Augmented Generation (RAG),DeepLearning.AI,Applications,RAG Systems,Intermediate,4,LLM Basics;Vector Databases,Free,https://www.deeplearning.ai/short-courses/,Vector Search;Embeddings;RAG Pipeline,No,2025-02,Intermediate
6,GA007,Course,LangChain for LLM Applications,DeepLearning.AI,Tools,LangChain,Intermediate,5,Python;LLM Basics,Free,https://www.deeplearning.ai/short-courses/,Chains;Memory;Agents;Tools,No,2025-01,Intermediate
7,GA008,Course,Large Language Models: From Theory to Practice,Stanford,Theory,LLM Theory,Advanced,40,Advanced Math;Deep Learning,Free,https://cs224n.github.io/,Model Architecture;Training;Evaluation,No,2024-12,Advanced
8,GA009,Course,Hugging Face NLP Course,Hugging Face,Tools,Transformers Library,Beginner,25,Python,Free,https://huggingface.co/course,Transformers;Datasets;Evaluation,No,2025-02,Foundation
9,GA010,Course,OpenAI API Fundamentals,OpenAI,Tools,OpenAI API,Beginner,10,Python,Free,https://platform.openai.com/docs,API Integration;GPT Models;Completion,No,2025-01,Foundation
10,GA011,Course,Claude API & Prompt Engineering,Anthropic,Tools,Claude API,Beginner,8,Python,Free,https://docs.anthropic.com,API Usage;Prompt Techniques;Vision,No,2025-02,Foundation
11,GA012,Course,Building AI Agents,DeepLearning.AI,Applications,Autonomous Agents,Advanced,6,LLM Basics;LangChain,Free,https://www.deeplearning.ai/short-courses/,Agent Design;Tool Use;Planning,No,2025-02,Advanced
12,GA013,Course,Vector Databases for Gen AI,DataStax,Tools,Vector Databases,Intermediate,5,Databases;Python,Free,https://www.datastax.com/generative-ai,Vector Search;Embeddings;Storage,No,2025-01,Intermediate
13,GA014,Course,GenAI for Code Generation,GitHub & Microsoft,Applications,Code Generation,Intermediate,6,Programming,Free,https://github.com/features/copilot,Copilot;Code Understanding;Optimization,No,2025-02,Intermediate
14,GA015,Course,Ethical AI & Responsible Gen AI,Coursera,Concepts,Ethics & Safety,Beginner,8,NaN,Free,https://www.coursera.org/learn/ai-ethics-gener...,Bias;Safety;Fairness;Governance,Yes,2025-01,Foundation
15,GA016,Book,Attention Is All You Need,Research Paper,Architecture,Transformers,Advanced,12,Advanced Math,Free,https://arxiv.org/abs/1706.03762,Transformer Architecture;Multi-head Attention,No,2017-06,Advanced
16,GA017,Book,The Illustrated Transformer,Blog,Architecture,Transformers,Intermediate,3,NaN,Free,https://jalammar.github.io/illustrated-transfo...,Visual Learning;Attention;Positional Encoding,No,2020-03,Architecture
17,GA018,Tutorial,Building LLM Applications with LangChain,Real Python,Tools,LangChain,Intermediate,4,Python;LLM Basics,Free,https://realpython.com/langchain-llm-applicati...,Integration;Chains;Memory,No,2024-12,Intermediate
18,GA019,Tutorial,Getting Started with RAG,Pinecone,Applications,RAG Systems,Intermediate,3,Vector Databases,Free,https://docs.pinecone.io/guides/getting-starte...,Semantic Search;Context Retrieval,No,2025-01,Intermediate
19,GA020,Documentation,OpenAI API Documentation,OpenAI,Tools,OpenAI API,Beginner,4,NaN,Free,https://platform.openai.com/docs/introduction,Models;Endpoints;Authentication,No,2025-02,Foundation
20,GA021,Documentation,Hugging Face Transformers Docs,Hugging Face,Tools,Transformers Library,Intermediate,6,Python,Free,https://huggingface.co/docs/transformers/,Library Usage;Model Loading;Fine-tuning,No,2025-02,Foundation
21,GA022,Tool,OpenAI ChatGPT,OpenAI,Tools,LLM Playground,Beginner,0,NaN,20,https://chat.openai.com,Prompting;Experimentation;Testing,No,2025-02,Foundation
22,GA023,Tool,Claude 3 (Anthropic),Anthropic,Tools,LLM Playground,Beginner,0,NaN,20,https://claude.ai,Advanced Prompting;Vision;Analysis,No,2025-02,Foundation
23,GA024,Tool,Google Bard/Gemini,Google,Tools,LLM Playground,Beginner,0,NaN,Free,https://gemini.google.com,Multimodal;Real-time;Integration,No,2025-02,Foundation
24,GA025,Tool,Copilot (GitHub/Microsoft),Microsoft,Tools,Code Generation,Beginner,0,NaN,10-19,https://github.com/features/copilot,Code Suggestion;Auto-completion,No,2025-02,Intermediate
25,GA026,Tool,LangChain Framework,LangChain,Tools,Application Framework,Intermediate,8,Python,Free,https://www.langchain.com,Chains;Memory;Agents;RAG,No,2025-02,Intermediate
26,GA027,Tool,LlamaIndex (GPT Index),LlamaIndex,Tools,RAG Framework,Intermediate,6,Python;Vector DB,Free,https://www.llamaindex.ai,Document Indexing;Query,No,2025-02,Intermediate
27,GA028,Tool,Pinecone Vector DB,Pinecone,Tools,Vector Databases,Beginner,4,Databases,Free-499,https://www.pinecone.io,Vector Search;Scaling,No,2025-02,Intermediate
28,GA029,Tool,Weaviate Vector DB,Weaviate,Tools,Vector Databases,Beginner,4,Databases,Free,https://weaviate.io,Semantic Search;Integration,No,2025-02,Intermediate
29,GA030,Tool,Chroma Vector DB,Chroma,Tools,Vector Databases,Beginner,3,Python,Free,https://www.trychroma.com,Lightweight;Easy Setup,No,2025-02,Intermediate
30,GA031,Specialization,Andrew Ng Generative AI Specialization,Coursera,Specialization,Complete Path,Intermediate,40,ML Fundamentals,49-199,https://www.coursera.org/specializations/gener...,LLMs;Prompt;Fine-tuning;RAG;Agents,Yes,2025-01,Comprehensive
31,GA032,Specialization,IBM Generative AI Engineering Professional Cer...,Coursera,Specialization,Complete Path,Intermediate,35,Python;ML Basics,39-199,https://www.coursera.org/professional-certific...,LLM Fundamentals;Tools;Applications,Yes,2025-02,Comprehensive
32,GA033,Project,Build a Chatbot with OpenAI API,Self-Directed,Applications,Chatbot Development,Beginner,5,Python;OpenAI API,Free,NaN,API Integration;NLP;UX,No,2025-01,Practical
33,GA034,Project,Implement RAG System with Pinecone,Self-Directed,Applications,RAG Implementation,Intermediate,8,Python;Vector DB;LLM,Free,NaN,Vector Search;Retrieval;Chunking,No,2025-02,Practical
34,GA035,Project,Fine-tune BERT for Text Classification,Self-Directed,Techniques,Transfer Learning,Intermediate,6,Python;Transformers;Deep Learning,Free,NaN,Fine-tuning;Classification;Evaluation,No,2025-01,Practical
35,GA036,Article,The Transformer Architecture Explained,Medium,Architecture,Transformers,Intermediate,2,NaN,Free,https://medium.com/the-dl/transformers-explain...,Visual Learning;Architecture,No,2024-06,Architecture
36,GA037,Article,Prompt Engineering Best Practices,OpenAI Blog,Techniques,Prompt Design,Beginner,1,NaN,Free,https://openai.com/blog/prompt-engineering-101,Techniques;Examples;Best Practices,No,2024-12,Intermediate
37,GA038,Article,Building Production LLM Applications,LangChain Blog,Applications,Production Systems,Advanced,3,LLM Basics;LangChain,Free,https://blog.langchain.dev,Deployment;Monitoring;Scale,No,2025-01,Advanced
38,GA039,Conference,NeurIPS (Neural Information Processing Systems),Multiple,Research,Latest Research,Advanced,20,Advanced Math;Research,Free,https://neurips.cc,Cutting-edge;Networking;Papers,No,2024-12,Research
39,GA040,Conference,ICML (International Conference on Machine Lear...,Multiple,Research,Latest Research,Advanced,20,Advanced Math;Research,Free,https://icml.cc,New Algorithms;Benchmarks,No,2025-02,Research
40,GA041,Community,Hugging Face Community,Hugging Face,Community,Peer Learning,Beginner,Self-paced,NaN,Free,https://huggingface.co/community,Discussions;Projects;Models,No,2025-02,Support
41,GA042,Community,DeepLearning.AI Discord,DeepLearning.AI,Community,Peer Learning,Beginner,Self-paced,NaN,Free,https://discord.gg/deeplearning,Q&A;Networking,No,2025-02,Support
42,GA043,Benchmark,SuperGLUE Benchmark,Benchmark,Evaluation,Model Evaluation,Advanced,Variable,NLP Knowledge,Free,https://super.gluebenchmark.com,Performance Metrics;Benchmarking,No,2024-12,Advanced
43,GA044,Benchmark,HELM (Holistic Evaluation of Language Models),CRFM,Evaluation,Comprehensive Eval,Advanced,Variable,LLM Knowledge,Free,https://crfm.stanford.edu/helm,Multi-dimensional Evaluation,No,2025-01,Advanced
44,GA045,Research Paper,Chain-of-Thought Prompting,Google,Techniques,Prompting Strategy,Advanced,3,LLM Basics,Free,https://arxiv.org/abs/2201.11903,Reasoning;Prompting;Few-shot,No,2022-01,Advanced
45,GA046,Research Paper,In-Context Learning in LLMs,DeepMind,Concepts,Model Behavior,Advanced,4,Transformers,Free,https://arxiv.org/abs/2212.04037,Learning Mechanisms;Few-shot,No,2022-12,Advanced
46,GA047,Research Paper,LoRA: Low-Rank Adaptation,Microsoft,Techniques,Parameter Efficiency,Advanced,3,Fine-tuning,Free,https://arxiv.org/abs/2106.09685,Efficient Tuning;PEFT,No,2021-06,Advanced
47,GA048,Podcast,Latent Space: GenAI Weekly,Latent Space,News & Trends,Industry Updates,Beginner,1,NaN,Free,https://www.latentspace.dev,Industry News;Interviews,No,2025-02,Support
48,GA049,Podcast,The Gradient Descent Podcast,Various,Research,Research Discussion,Intermediate,1.5,ML Knowledge,Free,https://thegradient.pub,Deep Dives;Expert Interviews,No,2025-01,Support
49,GA050,Newsletter,The Neuron,The Neuron,News & Trends,Weekly Updates,Beginner,0.5,NaN,Free,https://www.theneuron.ai,Curated News;Trends;Tools,No,2025-02,Support

### Read Excel File
#### Remember To import openpyxl For Excel Files

In [3]:
import openpyxl
excel_path="./File2.xlsx"
df2=pd.read_excel(excel_path)
df2.head()

,Resource_ID,Resource_Type,Resource_Name,Provider,Topic,Subtopic,Difficulty_Level,Duration_Hours,Prerequisites,Cost_USD,URL,Key_Skills,Certification_Available,Last_Updated,Learning_Path
0,GA001,Course,Generative AI Engineering,IBM,Fundamentals,LLM Basics,Beginner,20,NaN,0,https://www.ibm.com/generative-ai,LLM Architecture;Transformers;Prompting,Yes,2025-01,Foundation
1,GA002,Course,Google Generative AI Essentials,Google,Fundamentals,LLM Basics,Beginner,15,NaN,0,https://cloud.google.com/generative-ai,Gen AI Concepts;Google AI Tools,Yes,2025-02,Foundation
2,GA003,Course,Transformer Models and Attention,DeepLearning.AI,Architecture,Transformers,Intermediate,10,ML Fundamentals,Free,https://www.deeplearning.ai,Attention Mechanism;Self-Attention;Positional ...,No,2025-01,Architecture
3,GA004,Course,Prompt Engineering Masterclass,Andrew Ng,Techniques,Prompt Design,Beginner,8,NaN,49,https://www.deeplearning.ai/short-courses/,Few-shot Learning;Chain-of-Thought;Role Prompting,No,2025-02,Intermediate
4,GA005,Course,Fine-tuning LLMs,DeepLearning.AI,Techniques,Model Adaptation,Intermediate,6,ML Fundamentals;LLM Basics,Free,https://www.deeplearning.ai/short-courses/,PEFT;LoRA;QLoRA;Fine-tuning,No,2025-01,Advanced

### Creating Dataframe From Dictionary

In [4]:
songs={"Album":["Thriller","Black In Black","The Dark Side Of The Moon","The Bodyguard","Bat Out Of Hell"],
       "Released":[1982,1980,1973,1992,1977],
       "Length":["00:42:19","00:42:11","00:42:49","00:57:44","00:46:33"]}
songs_frame=pd.DataFrame(songs)
songs_frame.head()

                       Album  Released    Length
0                   Thriller      1982  00:42:19
1             Black In Black      1980  00:42:11
2  The Dark Side Of The Moon      1973  00:42:49
3              The Bodyguard      1992  00:57:44
4            Bat Out Of Hell      1977  00:46:33

#### Creating A New Data Frame One Column From The Table

In [5]:
p=songs_frame[["Released","Length"]]
print(p)

   Released    Length
0      1982  00:42:19
1      1980  00:42:11
2      1973  00:42:49
3      1992  00:57:44
4      1977  00:46:33

In [6]:
o=songs_frame["Album"]
print(o)

0                     Thriller
1               Black In Black
2    The Dark Side Of The Moon
3                The Bodyguard
4              Bat Out Of Hell
Name: Album, dtype: str

In [7]:
print(songs_frame.iloc[0:2,0:3])

            Album  Released    Length
0        Thriller      1982  00:42:19
1  Black In Black      1980  00:42:11

In [8]:
print(songs_frame["Released"])

0    1982
1    1980
2    1973
3    1992
4    1977
Name: Released, dtype: int64

### Using Unique In Pandas

In [9]:
unique=songs_frame["Released"].unique()
print(unique)

[1982 1980 1973 1992 1977]

### Inequality Operator

In [10]:
print(songs_frame["Released"]>1975)

0     True
1     True
2    False
3     True
4     True
Name: Released, dtype: bool

### Save As CSV

In [11]:
songs_frame.to_csv("Albums.csv")

In [12]:
print(songs_frame.head())

                       Album  Released    Length
0                   Thriller      1982  00:42:19
1             Black In Black      1980  00:42:11
2  The Dark Side Of The Moon      1973  00:42:49
3              The Bodyguard      1992  00:57:44
4            Bat Out Of Hell      1977  00:46:33

### Series
A Series is a one-dimensional labeled array in Pandas. It can be thought of as a single column of data with labels or indices for each element. You can create a Series from various data sources, such as lists, NumPy arrays, or dictionaries

In [13]:
data=[10,20,30,40,50]
s=pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [14]:
print(s[2])

30

In [15]:
print(s[1:3])

1    20
2    30
dtype: int64

In [16]:
print(songs_frame.iloc[0,2])

00:42:19

In [17]:
print(songs_frame["Released"])
print(songs_frame[["Album","Length"]])

0    1982
1    1980
2    1973
3    1992
4    1977
Name: Released, dtype: int64
                       Album    Length
0                   Thriller  00:42:19
1             Black In Black  00:42:11
2  The Dark Side Of The Moon  00:42:49
3              The Bodyguard  00:57:44
4            Bat Out Of Hell  00:46:33

In [18]:
p=songs_frame["Album"]
print(type(p))

<class 'pandas.Series'>

### Exercise 1

In [19]:
data={"Student":["David","Samuel","Terry","Evan"],"Age":[27,24,22,32],"Country":["UK","Canada","China","USA"],
      "Course":["Python","Data Structures","Machine Learning","Web Development"],"Marks":[85,72,89,76]}
df=pd.DataFrame(data)
df.head()

  Student  Age Country            Course  Marks
0   David   27      UK            Python     85
1  Samuel   24  Canada   Data Structures     72
2   Terry   22   China  Machine Learning     89
3    Evan   32     USA   Web Development     76

In [20]:
b=df["Marks"]
print(b)

0    85
1    72
2    89
3    76
Name: Marks, dtype: int64

In [21]:
c=df[["Country","Course"]]
print(c)

  Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

In [22]:
p=df["Student"]
print(type(p))

<class 'pandas.Series'>

### Using loc To Access The Course Of Specific Students

In [23]:
df=df.set_index("Student") ## We Are Needed To Set Index A Column
print(df.loc["Samuel","Course"])

Data Structures

In [24]:
print(df.loc["Terry","Country"])

China

In [25]:
print(df.loc["Evan","Country"])

USA

### Slicing Using iloc

In [26]:
print(df.iloc[1:3])

         Age Country            Course  Marks
Student
Samuel    24  Canada   Data Structures     72
Terry     22   China  Machine Learning     89

In [27]:
%pip install xlrd openpyxl

Requirement already satisfied: xlrd in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (2.0.2)
Requirement already satisfied: openpyxl in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in /Users/sayamdipdeychaklader/.conda/envs/myenv/lib/python3.11/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

### Exercise 2

In [28]:
import pandas as pd

In [2]:
customers={"OrderID":[1,2,3,4,5],"Product":["Laptop","Smartphone","Desk Chair","Notebook","Monitor"],
           "Category":["Electronics","Electronics","Furniture","Stationery","Electronics"],
           "Quantity":[2,3,5,10,1],"Price":[800,600,150,2,300],"OrderDate":["2022-01-10","2022-02-15","2022-03-12","2022-04-05","2022-05-21",],
           "CustomerCity":["New York","Los Angeles","Chicago","Houston","Miami"]}
df1=pd.DataFrame(customers)
df1

   OrderID     Product     Category  Quantity  Price   OrderDate CustomerCity
0        1      Laptop  Electronics         2    800  2022-01-10     New York
1        2  Smartphone  Electronics         3    600  2022-02-15  Los Angeles
2        3  Desk Chair    Furniture         5    150  2022-03-12      Chicago
3        4    Notebook   Stationery        10      2  2022-04-05      Houston
4        5     Monitor  Electronics         1    300  2022-05-21        Miami

### Changing File Format To Excel File

In [30]:
df1.to_excel("Customers.xlsx")

In [31]:
p=df1["Quantity"]
print(p)

0     2
1     3
2     5
3    10
4     1
Name: Quantity, dtype: int64

### l

In [32]:
print(df1[["Product","Category","Quantity"]])

      Product     Category  Quantity
0      Laptop  Electronics         2
1  Smartphone  Electronics         3
2  Desk Chair    Furniture         5
3    Notebook   Stationery        10
4     Monitor  Electronics         1

In [33]:
# Access the value on the first row and the first column
print(df1.iloc[0,0])

1

In [34]:
# Access the value on the second row and the first column
print(df1.iloc[1,0])

2

In [35]:
# Access the value on the first row and the third column
print(df1.iloc[0,2])

Electronics

In [36]:
# Access the value on the second row and the third column
print(df1.iloc[1,2])

Electronics

In [37]:
# Access the column using the name
df1=df1.set_index("Product")
print(df1.loc["Laptop","CustomerCity"])

New York

In [38]:
print(df1.loc["Smartphone","Price"])

600

### info Method

In [39]:
print(df1.info())

<class 'pandas.DataFrame'>
Index: 5 entries, Laptop to Monitor
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       5 non-null      int64
 1   Category      5 non-null      str
 2   Quantity      5 non-null      int64
 3   Price         5 non-null      int64
 4   OrderDate     5 non-null      str
 5   CustomerCity  5 non-null      str
dtypes: int64(3), str(3)
memory usage: 452.0+ bytes
None

In [41]:
customers2={"OrderID":[1,2,3,4,5],"CustomerName":["Sam","Angelina","Mathew","Michael","Lucas"]}
df2=pd.DataFrame(customers2)
df2.head()

   OrderID CustomerName
0        1          Sam
1        2     Angelina
2        3       Mathew
3        4      Michael
4        5        Lucas

### Merge Two Data Frames

In [43]:
merge_df=pd.merge(df2,df1,on=["OrderID","OrderID"])
merge_df.head()

   OrderID CustomerName     Category  Quantity  Price   OrderDate CustomerCity
0        1          Sam  Electronics         2    800  2022-01-10     New York
1        2     Angelina  Electronics         3    600  2022-02-15  Los Angeles
2        3       Mathew    Furniture         5    150  2022-03-12      Chicago
3        4      Michael   Stationery        10      2  2022-04-05      Houston
4        5        Lucas  Electronics         1    300  2022-05-21        Miami

### tail() Method
Displays the last n rows of the DataFrame.

In [48]:
merge_df.tail(2)

   OrderID CustomerName     Category  Quantity  Price   OrderDate CustomerCity
3        4      Michael   Stationery        10      2  2022-04-05      Houston
4        5        Lucas  Electronics         1    300  2022-05-21        Miami

### replace()
Replaces specific values in a column with new values.

In [56]:
merge_df=merge_df["CustomerName"].replace("Lucas","Leonardo",inplace=True)

/var/folders/7l/2xnthlg51zb55w1vmgw9x2br0000gn/T/ipykernel_57137/1045345543.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  merge_df=merge_df["CustomerName"].replace("Lucas","Leonardo",inplace=True)

In [58]:
print(merge_df)

0         Sam
1    Angelina
2      Mathew
3     Michael
4    Leonardo
Name: CustomerName, dtype: str